<?php

/**
 * This is the model base class for the table "car_generation".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CarGeneration".
 *
 * Columns in table "car_generation" available as properties of the model,
 * followed by relations of table "car_generation" available as properties of the model.
 *
 * @property integer $id
 * @property string $generation
 *
 * @property InfonCar[] $infonCars
 */
abstract class BaseCarGeneration extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'car_generation';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CarGeneration|CarGenerations', $n);
	}

	public static function representingColumn() {
		return 'generation';
	}

	public function rules() {
		return array(
			array('generation', 'length', 'max'=>255),
			array('generation', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, generation', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'infonCars' => array(self::HAS_MANY, 'InfonCar', 'car_generation_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'generation' => Yii::t('app', 'Generation'),
			'infonCars' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('generation', $this->generation, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}