<?php

/**
 * This is the model base class for the table "pupmai_paylate".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PupmaiPaylate".
 *
 * Columns in table "pupmai_paylate" available as properties of the model,
 * followed by relations of table "pupmai_paylate" available as properties of the model.
 *
 * @property integer $car_sale_id
 * @property integer $price
 *
 * @property CarSale $carSale
 */
abstract class BasePupmaiPaylate extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pupmai_paylate';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PupmaiPaylate|PupmaiPaylates', $n);
	}

	public static function representingColumn() {
		return 'car_sale_id';
	}

	public function rules() {
		return array(
			array('car_sale_id', 'required'),
			array('car_sale_id, price', 'numerical', 'integerOnly'=>true),
			array('price', 'default', 'setOnEmpty' => true, 'value' => null),
			array('car_sale_id, price', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'carSale' => array(self::BELONGS_TO, 'CarSale', 'car_sale_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'car_sale_id' => null,
			'price' => Yii::t('app', 'Price'),
			'carSale' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('car_sale_id', $this->car_sale_id);
		$criteria->compare('price', $this->price);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}