<?php

/**
 * This is the model base class for the table "brand".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Brand".
 *
 * Columns in table "brand" available as properties of the model,
 * followed by relations of table "brand" available as properties of the model.
 *
 * @property integer $id
 * @property string $brand_name
 *
 * @property InfonCar[] $infonCars
 */
abstract class BaseBrand extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'brand';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Brand|Brands', $n);
	}

	public static function representingColumn() {
		return 'brand_name';
	}

	public function rules() {
		return array(
			array('brand_name', 'required'),
			array('brand_name', 'length', 'max'=>255),
			array('id, brand_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'infonCars' => array(self::HAS_MANY, 'InfonCar', 'Brand_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'brand_name' => Yii::t('app', 'Brand Name'),
			'infonCars' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('brand_name', $this->brand_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}