<?php

/**
 * This is the model base class for the table "car_color".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CarColor".
 *
 * Columns in table "car_color" available as properties of the model,
 * followed by relations of table "car_color" available as properties of the model.
 *
 * @property integer $id
 * @property string $color
 *
 * @property InfonCar[] $infonCars
 */
abstract class BaseCarColor extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'car_color';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CarColor|CarColors', $n);
	}

	public static function representingColumn() {
		return 'color';
	}

	public function rules() {
		return array(
			array('color', 'required'),
			array('color', 'length', 'max'=>255),
			array('id, color', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'infonCars' => array(self::HAS_MANY, 'InfonCar', 'car_color_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'color' => Yii::t('app', 'Color'),
			'infonCars' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('color', $this->color, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}