<?php

/**
 * This is the model base class for the table "interest".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Interest".
 *
 * Columns in table "interest" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property double $interest
 *
 */
abstract class BaseInterest extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'interest';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Interest|Interests', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('interest', 'required'),
			array('interest', 'numerical'),
			array('id, interest', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'interest' => Yii::t('app', 'Interest'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('interest', $this->interest);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}