<?php

/**
 * This is the model base class for the table "type_spares".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TypeSpares".
 *
 * Columns in table "type_spares" available as properties of the model,
 * followed by relations of table "type_spares" available as properties of the model.
 *
 * @property integer $id
 * @property string $type_name
 *
 * @property InfoSpares[] $infoSpares
 */
abstract class BaseTypeSpares extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'type_spares';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'TypeSpares|TypeSpares', $n);
    }

    public static function representingColumn() {
        return 'type_name';
    }

    public function rules() {
        return array(
            array('type_name', 'required'),
            array('type_name', 'length', 'max' => 255),
            array('id, type_name', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'infoSpares' => array(self::HAS_MANY, 'InfoSpares', 'type_spares_id'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'type_name' => Yii::t('app', 'ປະ​ເພດ​ອາ​ໄຫຼ່'),
            'infoSpares' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('type_name', $this->type_name, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

}
