<?php

/**
 * This is the model base class for the table "sale_status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SaleStatus".
 *
 * Columns in table "sale_status" available as properties of the model,
 * followed by relations of table "sale_status" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 *
 * @property CarSale[] $carSales
 * @property SaleSpares[] $saleSpares
 */
abstract class BaseSaleStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sale_status';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SaleStatus|SaleStatuses', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>45),
			array('id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'carSales' => array(self::HAS_MANY, 'CarSale', 'sale_status_id'),
			'saleSpares' => array(self::HAS_MANY, 'SaleSpares', 'sale_status_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'carSales' => null,
			'saleSpares' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}