<?php

/**
 * This is the model base class for the table "placard".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Placard".
 *
 * Columns in table "placard" available as properties of the model,
 * followed by relations of table "placard" available as properties of the model.
 *
 * @property integer $id
 * @property string $date_note
 * @property string $date_placars
 * @property integer $infon_car_id
 * @property integer $customer_id
 * @property integer $pay_note
 * @property integer $pay_placar
 *
 * @property Customer $customer
 * @property InfonCar $infonCar
 */
abstract class BasePlacard extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'placard';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Placard|Placards', $n);
    }

    public static function representingColumn() {
        return 'date_note';
    }

    public function rules() {
        return array(
            array('infon_car_id, customer_id', 'required'),
            array('infon_car_id, customer_id, pay_note, pay_placar', 'numerical', 'integerOnly' => true),
            array('date_note, date_placars', 'safe'),
            array('date_note, date_placars, pay_note, pay_placar', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, date_note, date_placars, infon_car_id, customer_id, pay_note, pay_placar', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'customer' => array(self::BELONGS_TO, 'Customer', 'customer_id'),
            'infonCar' => array(self::BELONGS_TO, 'InfonCar', 'infon_car_id'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'date_note' => Yii::t('app', 'Date Note'),
            'date_placars' => Yii::t('app', 'Date Placars'),
            'infon_car_id' => null,
            'customer_id' => null,
            'pay_note' => Yii::t('app', 'Pay Note'),
            'pay_placar' => Yii::t('app', 'Pay Placar'),
            'customer' => null,
            'infonCar' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('date_note', $this->date_note, true);
        $criteria->compare('date_placars', $this->date_placars, true);
        $criteria->compare('infon_car_id', $this->infon_car_id);
        $criteria->compare('customer_id', $this->customer_id);
        $criteria->compare('pay_note', $this->pay_note);
        $criteria->compare('pay_placar', $this->pay_placar);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

}
