<?php

/**
 * This is the model base class for the table "staff".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Staff".
 *
 * Columns in table "staff" available as properties of the model,
 * followed by relations of table "staff" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $lastname
 * @property string $gender
 * @property string $age
 * @property string $address
 * @property string $tel
 * @property integer $salary
 * @property string $date
 * @property integer $status
 * @property integer $branch_id
 *
 * @property Branch $branch
 */
abstract class BaseStaff extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'staff';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Staff|Staff', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, lastname, gender, age, address, tel, salary, date, status, branch_id', 'required'),
			array('salary, status, branch_id', 'numerical', 'integerOnly'=>true),
			array('name, lastname', 'length', 'max'=>250),
			array('gender', 'length', 'max'=>5),
			array('age', 'length', 'max'=>3),
			array('tel', 'length', 'max'=>15),
			array('id, name, lastname, gender, age, address, tel, salary, date, status, branch_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'branch' => array(self::BELONGS_TO, 'Branch', 'branch_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'lastname' => Yii::t('app', 'Lastname'),
			'gender' => Yii::t('app', 'Gender'),
			'age' => Yii::t('app', 'Age'),
			'address' => Yii::t('app', 'Address'),
			'tel' => Yii::t('app', 'Tel'),
			'salary' => Yii::t('app', 'Salary'),
			'date' => Yii::t('app', 'Date'),
			'status' => Yii::t('app', 'Status'),
			'branch_id' => null,
			'branch' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('lastname', $this->lastname, true);
		$criteria->compare('gender', $this->gender, true);
		$criteria->compare('age', $this->age, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('tel', $this->tel, true);
		$criteria->compare('salary', $this->salary);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('branch_id', $this->branch_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}