<?php

/**
 * This is the model base class for the table "giveaway".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Giveaway".
 *
 * Columns in table "giveaway" available as properties of the model,
 * followed by relations of table "giveaway" available as properties of the model.
 *
 * @property integer $id
 * @property string $giveaway
 * @property integer $customer_id
 *
 * @property Customer $customer
 */
abstract class BaseGiveaway extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'giveaway';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Giveaway|Giveaways', $n);
	}

	public static function representingColumn() {
		return 'giveaway';
	}

	public function rules() {
		return array(
			array('giveaway, customer_id', 'required'),
			array('customer_id', 'numerical', 'integerOnly'=>true),
			array('id, giveaway, customer_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'customer' => array(self::BELONGS_TO, 'Customer', 'customer_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'giveaway' => Yii::t('app', 'Giveaway'),
			'customer_id' => null,
			'customer' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('giveaway', $this->giveaway, true);
		$criteria->compare('customer_id', $this->customer_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}