<?php

/**
 * This is the model base class for the table "acount_transfer".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AcountTransfer".
 *
 * Columns in table "acount_transfer" available as properties of the model,
 * followed by relations of table "acount_transfer" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $amount
 * @property string $date
 * @property integer $branch_id
 * @property string $status
 *
 * @property Branch $branch
 */
abstract class BaseAcountTransfer extends GxActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'acount_transfer';
    }

    public static function label($n = 1)
    {
        return Yii::t('app', 'AcountTransfer|AcountTransfers', $n);
    }

    public static function representingColumn()
    {
        return 'name';
    }

    public function rules()
    {
        return array(
            array('name, amount, date, branch_id', 'required'),
            array('amount, branch_id', 'numerical', 'integerOnly' => true),
            array('name', 'length', 'max' => 255),
            array('status', 'length', 'max' => 7),
            array('status', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, name, amount, date, branch_id, status', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'branch' => array(self::BELONGS_TO, 'Branch', 'branch_id'),
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ລຳ​ດັບ'),
            'name' => Yii::t('app', '​ຊື່​ຜູ້​ໂອນ'),
            'amount' => Yii::t('app', 'ຈຳ​ນວນ​ເງີນ'),
            'date' => Yii::t('app', '​ວັນ​ທີ'),
            'branch_id' => 'ສາ​ຂາ',
            'branch' => 'ສາ​ຂາ',
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('amount', $this->amount);
        $criteria->compare('date', $this->date, true);

        if (Yii::app()->user->checkAccess('Admin')) {
            $criteria->compare('branch_id', $this->branch_id);
        } else {
            $user = User::model()->findByPk(Yii::app()->user->id);
            $criteria->compare('branch_id', $user->branch_id);
        }
        $criteria->compare('status', $this->status, true);
        $criteria->order = "id DESC";

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
            'pagination' => array(
                'pageSize' => 200,
            ),
        ));
    }

}
