<?php

/**
 * This is the model base class for the table "paybefore".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Paybefore".
 *
 * Columns in table "paybefore" available as properties of the model,
 * followed by relations of table "paybefore" available as properties of the model.
 *
 * @property integer $id
 * @property integer $price
 * @property integer $customer_id
 *
 * @property Customer $customer
 */
abstract class BasePaybefore extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'paybefore';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Paybefore|Paybefores', $n);
    }

    public static function representingColumn() {
        return 'id';
    }

    public function rules() {
        return array(
            array('customer_id', 'required'),
            array('price, customer_id', 'numerical', 'integerOnly' => true),
            array('price', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, price, customer_id', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'customer' => array(self::BELONGS_TO, 'Customer', 'customer_id'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'price' => Yii::t('app', 'ຈຳ​ນວນ​ເງີນ'),
            'customer_id' => null,
            'customer' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('price', $this->price);
        $criteria->compare('customer_id', $this->customer_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

}
