<?php

/**
 * This is the model base class for the table "discount".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Discount".
 *
 * Columns in table "discount" available as properties of the model,
 * followed by relations of table "discount" available as properties of the model.
 *
 * @property integer $id
 * @property integer $discount
 * @property integer $customer_id
 *
 * @property Customer $customer
 */
abstract class BaseDiscount extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'discount';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Discount|Discounts', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('customer_id', 'required'),
			array('discount, customer_id', 'numerical', 'integerOnly'=>true),
			array('discount', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, discount, customer_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'customer' => array(self::BELONGS_TO, 'Customer', 'customer_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'discount' => Yii::t('app', 'Discount'),
			'customer_id' => null,
			'customer' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('discount', $this->discount);
		$criteria->compare('customer_id', $this->customer_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}