<?php

/**
 * This is the model base class for the table "car_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CarType".
 *
 * Columns in table "car_type" available as properties of the model,
 * followed by relations of table "car_type" available as properties of the model.
 *
 * @property integer $id
 * @property string $type_name
 *
 * @property InfonCar[] $infonCars
 */
abstract class BaseCarType extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'car_type';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'CarType|CarTypes', $n);
    }

    public static function representingColumn() {
        return 'type_name';
    }

    public function rules() {
        return array(
            array('type_name', 'required'),
            array('type_name', 'length', 'max' => 255),
            array('id, type_name', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'infonCars' => array(self::HAS_MANY, 'InfonCar', 'car_type_id'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'type_name' => Yii::t('app', 'ປະ​ເພດ​ລົດ'),
            'infonCars' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('type_name', $this->type_name, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

}
