<?php

/**
 * This is the model base class for the table "depts_month_pay".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DeptsMonthPay".
 *
 * Columns in table "depts_month_pay" available as properties of the model,
 * followed by relations of table "depts_month_pay" available as properties of the model.
 *
 * @property integer $id
 * @property integer $paid
 * @property string $status
 * @property string $date_pay
 * @property integer $infon_car_id
 * @property integer $customer_id
 * @property string $first_pay
 *
 * @property Customer $customer
 * @property InfonCar $infonCar
 */
abstract class BaseDeptsMonthPay extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'depts_month_pay';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DeptsMonthPay|DeptsMonthPays', $n);
	}

	public static function representingColumn() {
		return 'status';
	}

	public function rules() {
		return array(
			array('paid, status, date_pay, infon_car_id, customer_id', 'required'),
			array('paid, infon_car_id, customer_id', 'numerical', 'integerOnly'=>true),
			array('status, first_pay', 'length', 'max'=>1),
			array('first_pay', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, paid, status, date_pay, infon_car_id, customer_id, first_pay', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'customer' => array(self::BELONGS_TO, 'Customer', 'customer_id'),
			'infonCar' => array(self::BELONGS_TO, 'InfonCar', 'infon_car_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'paid' => Yii::t('app', 'Paid'),
			'status' => Yii::t('app', 'Status'),
			'date_pay' => Yii::t('app', 'Date Pay'),
			'infon_car_id' => null,
			'customer_id' => null,
			'first_pay' => Yii::t('app', 'First Pay'),
			'customer' => null,
			'infonCar' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('paid', $this->paid);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('date_pay', $this->date_pay, true);
		$criteria->compare('infon_car_id', $this->infon_car_id);
		$criteria->compare('customer_id', $this->customer_id);
		$criteria->compare('first_pay', $this->first_pay, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}